# Generated by Django 3.0.4 on 2020-04-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0002_school_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='state',
            new_name='region',
        ),
    ]
