# Generated by Django 3.0.4 on 2020-04-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0003_auto_20200415_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lga',
            old_name='state',
            new_name='region',
        ),
    ]
