# Generated by Django 3.0.4 on 2020-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0004_auto_20200415_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sch_logo',
            field=models.FileField(null=True, upload_to='images/sch_logo'),
        ),
    ]
