# Generated by Django 3.0.4 on 2020-04-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0005_school_sch_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='exam_quota_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='exam_quota_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='exam_quota_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='hod_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='index_quota_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='indexed',
            field=models.IntegerField(null=True),
        ),
    ]
