# Generated by Django 3.0 on 2022-07-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('schPortal', '0006_indexing_grade3_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_of_origin', to='cities_light.Country'),
        ),
    ]
