# Generated by Django 3.0.4 on 2020-04-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0006_auto_20200417_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
