# Generated by Django 3.0 on 2022-07-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0007_examregistration_country_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examregistration',
            name='country_of_origin',
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='lga_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='lga_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='state_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
