# Generated by Django 3.0.4 on 2020-04-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0008_auto_20200420_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examregistration',
            old_name='offfice_address',
            new_name='office_address',
        ),
        migrations.RenameField(
            model_name='examregistration',
            old_name='referee_address1',
            new_name='referee_email1',
        ),
        migrations.RenameField(
            model_name='examregistration',
            old_name='referee_address2',
            new_name='referee_email2',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='religion',
        ),
     
    ]
