# Generated by Django 3.0.4 on 2020-04-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0009_auto_20200420_2021'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='indexing',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
