# Generated by Django 3.0.4 on 2020-04-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0010_auto_20200423_0836'),
    ]

    operations = [
  
        migrations.AddField(
            model_name='examregistration',
            name='residential_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
