# Generated by Django 3.0.4 on 2020-04-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0011_auto_20200424_0732'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='examregistration',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='lga_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lga_of_origin', to='schPortal.LGA'),
        ),
    ]
