# Generated by Django 3.0.4 on 2020-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0012_auto_20200424_1015'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='examregistration',
            name='submitted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
