# Generated by Django 3.0.4 on 2020-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0013_auto_20200424_1022'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='school',
            name='updated_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
