# Generated by Django 3.0.4 on 2020-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0014_auto_20200424_1446'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
