# Generated by Django 3.0.4 on 2020-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0017_auto_20200424_1530'),
    ]

    operations = [
     
        migrations.AlterField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
