# Generated by Django 3.0.4 on 2020-05-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0018_auto_20200424_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='indexed',
        ),
    
    ]
