# Generated by Django 3.0.4 on 2020-05-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0019_auto_20200501_1155'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='indexing',
            name='exam_sitting',
            field=models.IntegerField(default=1),
        ),
    ]
