# Generated by Django 3.0.4 on 2020-05-03 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0020_auto_20200502_1501'),
    ]

    operations = [
      migrations.AddField(
            model_name='examregistration',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='schPortal.School'),
        ),
    ]
