# Generated by Django 3.0.4 on 2020-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0021_auto_20200503_1148'),
    ]

    operations = [
 
        migrations.AddField(
            model_name='examregistration',
            name='religion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='postal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
