# Generated by Django 3.0.4 on 2020-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0023_auto_20200508_1430'),
    ]

    operations = [
    
        migrations.AddField(
            model_name='indexing',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexing',
            name='unapproved',
            field=models.BooleanField(default=False),
        ),
    ]
