# Generated by Django 3.0.4 on 2020-05-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0024_auto_20200509_1108'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='indexing',
            name='o_level_cert1',
            field=models.ImageField(blank=True, null=True, upload_to='images/OlevelResult'),
        ),
        migrations.AddField(
            model_name='indexing',
            name='o_level_cert2',
            field=models.ImageField(blank=True, null=True, upload_to='images/OlevelResult'),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='marriage_cert',
            field=models.ImageField(blank=True, null=True, upload_to='images/indexing/marriage_cert'),
        ),
    ]
