# Generated by Django 3.0.4 on 2020-06-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0026_auto_20200509_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examregistration',
            name='referee_phone2',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='school',
        ),
        migrations.RemoveField(
            model_name='school',
            name='lga',
        ),
    ]
